# Auto-generated by IDE. All changes by user will be lost!
# Created at 11/22/12 10:09 AM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/UrbanAirshipAPI.cpp \
    $$BASEDIR/src/UrbanAirshipClient.cpp \
    $$BASEDIR/src/main.cpp

HEADERS +=  \
    $$BASEDIR/src/UrbanAirshipAPI.hpp \
    $$BASEDIR/src/UrbanAirshipClient.hpp

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

