#!/bin/bash
PJSIPCHECKOUTDIR="pjsip-checkout"
mkdir $PJSIPCHECKOUTDIR
pushd $PJSIPCHECKOUTDIR
wget http://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-0.1.3.tar.gz
tar xvf opencore-amr-0.1.3.tar.gz
svn checkout http://svn.pjsip.org/repos/pjproject/trunk
popd

